### ISSUE TITLE
Can Play Video that MediaDetector Can't Read

### ISSUE THREAD

**Issue by Deadpikle** [Sascha-L/WPF-MediaKit#11]
Hey all,

I'm having some issues getting the WPF-MediaKit libray MediaDetector class to read in some video files -- specifically, some mp4 files. I can play them (graphically speaking) just fine using the library, but MediaDetector doesn't seem to be able to load the files, which is a feature I need so that I can save video thumbnails. LoadMedia() thinks that there are no streams.

Seeing as how both the playback functionality and MediaDetector use DirectShow, I'm a bit confused as to why this is happening. I've gotten MediaDetector to work before, but I reinstalled my DirectShow video codecs and suddenly it doesn't work. 

The filters I am attempting to use are here: https://github.com/Nevcairiel/LAVFilters . Before installing the filters, I cannot play the specified mp4 files, but after I install them, MediaKit is able to play them...so the filters themselves seem to be fine.

Perhaps the put_Filter() function of DirectShow.DES.IMediaDet needs to be used to load filters first?

Thanks for any assistance.

**Comment by simonbuehler** [comment]
hi, 
ran into the same issue when trying to get the AvgFrameRate from a File (mjpeg).
Did you solve this issue somehow?

**Comment by Deadpikle** [comment]
@simonbuehler : No, I wasn't able to figure out how to solve the issue unfortunately.

I actually ending up not using WPF-MediaKit at all in my project. I needed to take dynamic screenshots of a video on a background thread without rendering a MediaElement to the screen, and I actually figured out that you can do so via native C# WPF code (this is possible because MediaElement can actually natively play MP4; don't know about mjpeg).

I can't post much of the code due to it being for my client, but if you need to do something similar, I'll point you to http://stackoverflow.com/questions/423373/how-do-i-write-a-method-to-open-start-playing-then-return-the-duration-of-an-a and then tell you that you can get an image of a MediaPlayer element that you've created and used to open media with...
```
RenderTargetBitmap bmp = new RenderTargetBitmap(640, 480, 96, 96, PixelFormats.Pbgra32);
DrawingVisual dv = new DrawingVisual();
using (DrawingContext dc = dv.RenderOpen())
{
    dc.DrawVideo(player, new Rect(0, 0, 640, 480));
}
bmp.Render(dv);
```

Good luck! Sorry I wasn't able to help.

**Comment by xmedeko** [comment]
For grabbing an image see the [Wiki FAQ](https://github.com/Sascha-L/WPF-MediaKit/wiki/FAQ#how-to-grab-a-screenshot) and offscreen see [Wiki Headless Examples](https://github.com/Sascha-L/WPF-MediaKit/wiki/Headless-Examples).

I do not know how ti fix the `MediaDetector` and since nobody has offered a PR to fix that I am closing the issue.
