### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by idanpat8** [Sascha-L/WPF-MediaKit#14]
Hi,

I had the previous version of mediakit and I try to replace it to the new one.
Nothing is played, so I check the dll dependencies and there seems to be a lot of missing dll's.
Should I install something else in order for this to work?

(by the way, the test app is working)

thanks!

**Comment by xmedeko** [comment]
You should install just DirectShowLib, or try the new NuGet Package: https://www.nuget.org/packages/WPFMediaKit/
