### ISSUE TITLE
60 frames or above HD videos application freezes

### ISSUE THREAD

**Issue by alexprvn** [Sascha-L/WPF-MediaKit#15]
Dear Sacha,
i am trying a application which uses more than 10 player in a window also number of player changes
dynamically for every 10 min while trying what i could face is

whole application hangs till videos of 60 frames or more( all major format videos) of any resolution stops or ends.
some times it happen from the first video or some times playing 3 or 5 times.

if it is a 30 frames video it is smooth. please help me find the issue it might help me in many ways.

Thanks

**Comment by xmedeko** [comment]
What do you mean by 60 frames video? You mean 60FPS video? 

Also try the newest source, or EVR presenter with DXVA enabled. The DXVA has to be enabled in the codecs setting. 

If you used the player only, why do you not use WPF `MediaElement`?

**Comment by xmedeko** [comment]
Closing, probably fixed, the reported does not response.
