### ISSUE TITLE
Here is a small example: how to use MediaKit

### ISSUE THREAD

**Issue by DarioSalcedo** [Sascha-L/WPF-MediaKit#18]
Hey guys, this is just a small example of how to use this tool.

en primer lugar tuve problemas al intentar reproducir algo, lo que hice para solucionar el problema fue
cambiar la plataforma de destino a x86 y volver a compilar la librería, también actualice la librería DirectShowLib-2005.dll  por  directshowlib-2008.dll y empece a  jugar un poco.

instale K-Lite_Codec_Pack_1225_Basic y listo, funciono.

adjunto el ejemplo por si a  alguien le sirve y de paso me ayuda a mejorar algunos aspectos. Espero que este control trabaje 24/7 y no tenga problemas de perdida de memoria "memory leaks"

PD: no encontré la propiedad "ScrubbingEnabled", haber si alguno logra solucionarlo, saludos desde Peru.

IDE: VS 2015 community edition

https://mega.nz/#!SldGiKpa!NjFeqNOgH4BqFK0JIXvxC_eO89xD4DUdwWgwm7hlQ5Q

**Comment by xmedeko** [comment]
Please, we try to stick with the English for the documentation. Submit a PR if you would like to contribute to the doc, or post an English text, thanks.
