### ISSUE TITLE
cannot play m3u8 streams

### ISSUE THREAD

**Issue by hasan-hasanov** [Sascha-L/WPF-MediaKit#19]
Hello can anyone managed to play m3u8 streams with mediakit? Whatever Url I am setting it always gives me the same error: Could not render any streams from the source Uri.

I am sure the streams are working becaouse I can play them with my UWP app's media element. Is this an issue or I am doing something wrong? Here is my code:

```
        private void MediaPlayer_Loaded(object sender, RoutedEventArgs e)
        {
            MediaPlayer.LoadedBehavior = WPFMediaKit.DirectShow.MediaPlayers.MediaState.Manual;
            MediaPlayer.Source = new Uri(
                @"Some Uri that ends with m3u8",
                UriKind.RelativeOrAbsolute);
            MediaPlayer.Play();
        }
```

```
<controls:MediaUriElement
            x:Name="MediaPlayer"
            Grid.Row="0"
            Grid.RowSpan="2"
            Loaded="MediaPlayer_Loaded"
            Stretch="Fill"
            MediaFailed="MediaPlayer_MediaFailed"/>

```

I am subscribed to MediaFailed event which fires twice. First time it gives me: Could not render any streams from the source Uri. Second time is object reference not set error. I cannot figure out which object since there is not any indication. Any help is appriciated.

**Comment by xmedeko** [comment]
WPF-MediaKit itself cannot play m3u8 (or any other media formats). It always depends on the codecs installed.

Do not know much about the m3u8, but LAV Splitter should be able to play it. Try to enforce to use the LAV Splitter. However, it's possible the support may be limited and maybe it cannot play all m3u8.
