### ISSUE TITLE
MediaUriElement can not find resource “effects/deepercolor.ps”

### ISSUE THREAD

**Issue by LazyCuteLion** [Sascha-L/WPF-MediaKit#40]
when set DeeperColor="True"

**Comment by xmedeko** [comment]
May you chaneg the title to English and describe your problem better?

**Comment by xupefei** [comment]
The title is (in English)

> MediaUriElement can not find resource “effects/deepercolor.ps”

**Comment by patricknro** [comment]
Hi!
I created MediaUriElement in my screen and put source file "Video.mp4" but it doesn't play video. Why it happened?

Remember that the files are in root location.

**Comment by xmedeko** [comment]
@patricknro see #41 and next time please to not post to the offtopic thread.

**Comment by xmedeko** [comment]
Check, if the `DeeperColorEffect.AssemblyShortName` is properly set, i.e. if the URI in the ctor is properly constructed.

**Comment by birdcpe25** [comment]
I tried build using Release and set Effects/DeepColor.ps as Resource, It's all work properly.

**Comment by xmedeko** [comment]
Thanks, I've fixed the csproj.

The setting to the Release is not necessary, it's enough to recompile the project in Debug.
