### ISSUE TITLE
VideoCaptureElement is black out and D3DImage.IsFrontBufferAvailable is always false

### ISSUE THREAD

**Issue by Rhuaer** [Sascha-L/WPF-MediaKit#42]
I got a problem  when I did some operations as below,

- Turn UAC level to high,
- Create videoCaptureElement and start to preview with a  camera device,
- Set videoCaptureElement to pause and minimize the application,
- Run other application as administrator,
- Restore the application 
- The videoCaptureElement is black out most of time.

I noticed D3DImage.IsFrontBufferAvailable was always false when videoCaptureElement was black out.  D3DImage.IsFrontBufferAvailable never turned back to ture, and D3DImage.IsFrontBufferAvailableChanged never fired after that.

So is it safe to ignore D3DImage.IsFrontBufferAvailable?
It seems that's ​recommended by this [post](http://marcangers.com/2015/02/).

**Comment by xmedeko** [comment]
Seems like the application has lost the access to the hardware rendering, similar to #3?
