### ISSUE TITLE
WorkDispatcher.DispatcherThread: Property has no public setter

### ISSUE THREAD

**Issue by JohannesDrexler** [Sascha-L/WPF-MediaKit#47]
The class WPFMediaKit.Threading.WorkDispatcherObject has no public setter.
Can this be changed to get a setter ?

**Comment by xmedeko** [comment]
What's your use case, why do you need that?

**Comment by JohannesDrexler** [comment]
I am using the MediaDetector in a service to create thumbnails for Videos. 
Because of multithreading the method "VerifyAccess()" often throws "Not the same thread". I have bypassed this by assigning the dispatcherthread like in the code below: 

`MediaDetector mediaDec = new MediaDetector();
mediaDec.GetType().InvokeMember("m_dispatcherThread", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.SetField, null, mediaDec.Dispatcher, new object[] { Thread.CurrentThread });`

In a scenario with many threads it would be nice to have a bit more control about the DispatcherThread and using a setter would be a better solution than having to set it using the 'InvokeMember'-method

**Comment by JohannesDrexler** [comment]
I am using the WpfKit in a service to capture Thumbnails of videos and stuff like that. Because of multithreading and using of tasks i need do assign the DispatcherThread to avoid erros in "VerifyAccess()"

**Comment by xmedeko** [comment]
I am not sure if you can safely obey `VerifyAccess` this way - i.e. if it does not bring more problems.
You can use `Dispatcher.BeginInvoke(...)` to run your task on the Dispatcher thread.

**Comment by JohannesDrexler** [comment]
Dispatcher.BeginInvoke works well for me. You can close that issue if you want to

**Comment by xmedeko** [comment]
Note: you can use also FFMPEG to capture video thumbnails, e.g. https://github.com/vladjerca/FFMpegSharp

**Comment by JohannesDrexler** [comment]
This would be also an option but i try to keep the application i work on as tiny as possible.
That's why i am trying to use your package ;)

**Comment by xmedeko** [comment]
It's not my package, it's a community package :-). I am just helping to maintain it.
Can you publish a Wiki page at https://github.com/Sascha-L/WPF-MediaKit/wiki how to do video thumbnail with this project when running as a service (without display)? Sometime people ask for this, thanks.

**Comment by xmedeko** [comment]
@JohannesDrexler can you help tp solve #11 - how to get video thumbnails offscreen?
