### ISSUE TITLE
MediaDetector: LoadFile(string fileName) swallows exception

### ISSUE THREAD

**Issue by JohannesDrexler** [Sascha-L/WPF-MediaKit#48]
https://github.com/Sascha-L/WPF-MediaKit/blob/8a251248c629e03feeccec1f5b627450bf9c96b2/Source/DirectShow/MediaPlayers/MediaDetector.cs#L217

The exception does not contain the previously catched exception. The information that loading failed is useless without the exception included....

**Comment by JohannesDrexler** [comment]
I changed that and opened a pullrequest #49

**Comment by xmedeko** [comment]
Thanks for opening this issue and the PR. We should check and improve exception throwing in the whole project:
- Create `WPFMediaKitException` and change all `throw Exception` to `throw WPFMediaKitException`.
- Include nested exception when re throwing.

Would you like to make these improvements in your PR?

**Comment by JohannesDrexler** [comment]
I will do theese improvements in my PR :)

**Comment by JohannesDrexler** [comment]
i updated the PR-branch
