### ISSUE TITLE
How use MediaUriPlayer without MediaUriElement? 

### ISSUE THREAD

**Issue by Conquistador** [Sascha-L/WPF-MediaKit#50]
Hello, 
I need to play .m3u8 files from WindowsService. 
Now I'm using something like this:
```cs 
private static MediaUriElement _playerElement;
static void Main(string[] args)
{
	var thread = new Thread(ThreadMethod);
	thread.SetApartmentState(ApartmentState.STA);
	thread.Start();        
	
	Console.ReadKey();
}
private static void ThreadMethod()
{
	_playerElement = new MediaUriElement();

	_playerElement.BeginInit();
	_playerElement.EndInit();

	_playerElement.Source = new Uri("http://[mypath].m3u8");
	_playerElement.Play();
}
```
How I can use MediaUriPlayer directly?

**Comment by xmedeko** [comment]
Do you show the video on the screen in WPF? If so, why the `MediaUriElement` is not good for you?

**Comment by Conquistador** [comment]
No, I just play the sound using the .m3u8 file.

**Comment by xmedeko** [comment]
If you need to play just a sound, then this project is maybe overkill, since it focuses on video.  Do you need DirectShow? Maybe another solutions, like [WMLib](https://msdn.microsoft.com/en-us/library/windows/desktop/dd562692(v=vs.85).aspx) may be sufficient for you?

Anyway, I think you can use `MediaUriPlayer` directly. I have not tried it, though.  Try to construct it, set `Source` and `Play()`.

**Comment by Conquistador** [comment]
To use WMLib or Naudio or CScore, I need to implement a module for parsing and managing playback of playlists that are contained in m3u8 files. WPFMediaKit can do this out of the box.

If just set the `Source` and `Play()` in `MediaUriPlayer`, I receive:
_An unhandled exception of type 'System.InvalidOperationException' occurred in WPFMediaKit.dll
Additional information: Not the same thread_

So I think that a more complicated initialization procedure is required...

**Comment by xmedeko** [comment]
See the issue #47, try `Dispatcher.BeginInvoke`.

**Comment by Conquistador** [comment]
Thanks for the help! 
I found that it's enough to add only one line and everything starts working!
```cs
_player.EnsureThread(ApartmentState.MTA);
```
The whole simplest example of how to play m3u8 files from a console application:
```cs
class Program
{
	private static MediaUriPlayer _player;
	static void Main(string[] args)
	{
		_player = new MediaUriPlayer();

		_player.EnsureThread(ApartmentState.MTA);
		_player.Dispatcher.BeginInvoke(() =>
		{
			_player.Source = new Uri("[MyUri].m3u8");
			_player.Play();
		});
		Console.ReadKey();
	}
}
```
