### ISSUE TITLE
Wrong condition in D3DRender.D3DImageIsFrontBufferAvailableChanged

### ISSUE THREAD

**Issue by Rhuaer** [Sascha-L/WPF-MediaKit#61]
## Hardware configuration
1. Intel Celeron CPU J1900 1.99GHZ
2. RAM:4G
3. Integrated graphics card:Intel HD Graphics

## Reproduce
1. Preview camera with wpfMediaKit
2. Put the computer to sleep
3. Wake the computer up after step 2
4. Repeat setp 1-3 above multiple times, the application will be black out.

## Other information
- D3DDevice lost when application is black out
- Notice the event D3DImage.IsFrontBufferAvailableChanged is fired, but I find some problem in method, D3DRender.D3DImageIsFrontBufferAvailableChanged.
   ```csharp
        private void D3DImageIsFrontBufferAvailableChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            //I think the condition below is wrong. When D3D device lost, D3DImage.IsFrontBufferAvailable is false all the time.
            if (!D3DImage.IsFrontBufferAvailable)
                return;

            m_newSurfaceAvailable = true;
            SetBackBufferInternal(m_pBackBuffer);
        }
   ```

**Comment by xmedeko** [comment]
@Rhuaer is this issue similar/duplicate to #42 and #3?

**Comment by Rhuaer** [comment]
@xmedeko yeah, I will try it with BobDeCuir's suggestion.
Thanks.

**Comment by xmedeko** [comment]
May you suggest some PR, or some HOWTO manual for other users?

**Comment by Rhuaer** [comment]
@xmedeko I have created a pull request just now. see #62
