### ISSUE TITLE
Failed to load .wmv 

### ISSUE THREAD

**Issue by galastur** [Sascha-L/WPF-MediaKit#7]
Hello,

I have download the project and add a button to try to grab a video frame from a .wmv file. The file opens and plays fine. Then I hit the grab frame, and it fails when it tries to load the media. Could you please let me know what am I doing wrong? Thanks

```
      int hr = m_mediaDet.put_Filename(m_filename); --> hr value comes as -2147024773
        DsError.ThrowExceptionForHR(hr);
```

   at WPFMediaKit.DirectShow.MediaPlayers.MediaDetector.LoadMedia(String filename) in E:\Libraries\External\WPF-MediaKit-master\Source\DirectShow\MediaPlayers\MediaDetector.cs:line 217
   at Test_Application.MainWindow.btnGrabFrame_Click(Object sender, RoutedEventArgs e) in E:\Libraries\External\WPF-MediaKit-master\Test Application\MainWindow.xaml.cs:line 49

``` javascript
private void btnGrabFrame_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                WPFMediaKit.DirectShow.MediaPlayers.MediaDetector det = new WPFMediaKit.DirectShow.MediaPlayers.MediaDetector();
                if (!det.HasVideo)
                {
                    string path = mediaUriElement.Source.AbsolutePath;
                    det.LoadMedia(path);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("ERROR: " + ex.ToString());
            }


        }
```

**Comment by skaterlui** [comment]
The detector has to be loaded before the mediafile is used with mediaUriElement.
When the file is used by mediaUriElement process the load will throw an exception.
Load it before setting the source of mediaUriElement.

**Comment by xmedeko** [comment]
If you need a screenshot while playing, try the new `D3DRenderer.CloneSingleFrameImage()` method.
