### ISSUE TITLE
How to clone a video from one WPFMediaKit element to another?

### ISSUE THREAD

**Issue by tenisak** [Sascha-L/WPF-MediaKit#72]
Is it possible to copy a video that runs in one WPFMediaKit element to run at the same time in another element?
What is the Goal: Video preview, controls, etc. will be on the first monitor. The second monitor (projector or large TV) displays the same video on full screen.

**Comment by xmedeko** [comment]
Yes, see `D3DRenderer.CloneD3DRenderer()`.

**Comment by tenisak** [comment]
Thank you for quick response. To tell the truth, I do not know how to use it. I tried searching in the sample application, but there it is not used. I found it [in the code here](https://github.com/Sascha-L/WPF-MediaKit/blob/af475371a0828945aa69b437413f31dc10c8214b/Source/DirectShow/Controls/D3DRenderer.cs#L610), but I do not know how to do it. (I'm using Capture Device, not video playback.)
Can you advise me how to use `CloneD3DRenderer` to clone an image from a camera to another element?

**Comment by tenisak** [comment]
It's easier than I expected :-) Thanks a lot!
I added it as an example to the basic examples in the wiki. I hope, it does not matter ;-)

**Comment by xmedeko** [comment]
+1 for the Wiki enhancement.
