### ISSUE TITLE
Video is rotated when playing

### ISSUE THREAD

**Issue by wj985712588** [Sascha-L/WPF-MediaKit#75]
the direction of some video file is not correctly,
who can tell me how to  correct it ?
thanks

**Comment by xmedeko** [comment]
What to you mean direction? How is behaviour in other players - MPC-HC?

**Comment by wj985712588** [comment]
the video media is Rotated when playing

**Comment by xmedeko** [comment]
This is not a poor issue report. I repeat: [read this before posting an issue](https://github.com/Sascha-L/WPF-MediaKit/blob/master/.github/issue_template.md).
Have you tried it on another machine?
What's the result in another video players WMP, MPC-HC, VLC, ...?
Describe the video format, provide a link to video if you can.
What codecs are used, see GraphStudioNext or debug this project.

**Comment by wj985712588** [comment]
yeah，this issue is related to Nevcairiel/LAVFilters#190.
the problem is happend on win10 machine wpf apps
the win10 wmp player and other player such as potplayer ... is normal
the video format is .mp4,it is Shot on the phone
i just use the LavFilters.

I guess that the reason may be the decoder(ffmpeg)

**Comment by xmedeko** [comment]
And what about any other DirectShow player, like MPC-HC? If the MPC-HC plays it rotated, too, then it's a problem of the codec - LavFilters.

**Comment by wj985712588** [comment]
the mpc-hc player performs normal

**Comment by xmedeko** [comment]
MPC-HC should use same codecs as WPF-MediaKit, but there may be some exceptions, since WPF-MediaKit tries to favour LAV Codecs. So you should trye GraphStudioNext to check, what codecs are used by default - by MPC-HC and then debug the WPF-MediaKit `MediaUriPlayer.OpenSource()` to see what codecs are used here.

**Comment by xmedeko** [comment]
FFMpeg is another technology. Generally, Windows players uses three major technologies DirectShow, Windows Media Foundation and ffmpeg. The WPF-MediaKit is based on DirectShow. So you have to check WPF-MediaKit with other DirectShow players, e.g. the MPC-HC.
If the MPC-HC plays the file well, then you have to check, what codecs it uses. see my previous post about GraphStudioNext (from K-Lite codecs, see [Wiki](https://github.com/Sascha-L/WPF-MediaKit/wiki/Codecs)).

**Comment by wj985712588** [comment]
I think,the ghost windows system may not contain the Windows Media Player or Windows Media Center,so that the video or audio may not be played.

**Comment by wj985712588** [comment]
Also, in my wpf apps and the system install k-lite codec pack,the video is also rotated.

**Comment by xmedeko** [comment]
In regards of  WPF `MediaElement`: it uses Windows Media Foundation, like Windows Media Player, but does not Windows Media Player itself to be installed.

In regards of the video rotated in the WPF-MediaKit: you have to analyze real codecs used, see my **2** posts above.

**Comment by wj985712588** [comment]
DirectShowUtil.AddFilterToGraph(m_graph, VideoDecoder, Guid.Empty);
m_graph = {DirectShowLib.FilterGraphNoThread}
VideoDecoder = "LAV Video Decoder"

**Comment by wj985712588** [comment]
the method MediaUriPlayer.DumpGraphInfo(string fileName) is not Executed。

**Comment by xmedeko** [comment]
Yes, it isn't. You have to call ut after the video is loaded (opened).

**Comment by xmedeko** [comment]
I see from Nevcairiel/LAVFilters#190 that you have to use a renderer supporting rotation. Currently, WPF-MediaKit supports EVR or VMR9 renderers, try them both. I do not know if any of them supports rotation.
