### ISSUE TITLE
WPF-MediaKit not working with webcam

### ISSUE THREAD

**Issue by msadowski** [Sascha-L/WPF-MediaKit#77]
I'm trying to run a Test Application from the repo to see the output of a webcam. The program works as expected on 2 of 3 of my computers (all of them on Windows 10). I installed K-Lite codec pack but that didn't seem to help. I run GraphStudioNext, inserted video source and video renderer and it displays the camera correctly.

Are there any further steps I can take to debug the problem? 

### Before reporting an issue, check and answer the following points if they are valid for your case:

* Does the problem emerge on different HW, OS versions? Describe your HW configuration.
HP Laptop with Windows 10 Home, dual graphics card (Intel HD 630, Geforce GTX 1050), built-in camera and Logitech HD Pro Webcam C920.
* Is the problem caused by the DirectShow codecs or the player itself?
Not sure
  * Try the clean install of [DirectShow codecs](https://github.com/Sascha-L/Sascha-L/WPF-MediaKit/wiki/Codecs).
Tried it, didn't seem to help
  * Try another DirectShow player (e.g. MPC-HC).
Possibly not relevant?
  * Use GraphStudioNext to see, what codecs are used for your video.
Possibly not relevant?
* Describe the video format. Consider providing a HTTP link to download a video which causes the problem.
Direct connection to webcam

Any help would be highly appreciated

**Comment by xmedeko** [comment]
Do not understand what's the problem: you have 3 machines, the problem is on one machine only? Is the problem with the built-in camera or Logitech HD Pro Webcam C920?

**Comment by msadowski** [comment]
@xmedeko Yes, the problem is on one machine only. It doesn't show camera feed for any of those two cameras (both built-in camera and Logitech C920).

**Comment by msadowski** [comment]
Sorry for the late reply. Unfortunately the system I've been experiencing this problem on has been wiped and I cannot reproduce it anymore. I'm closing this issue.
