### ISSUE TITLE
stop close and xp issues with the player

### ISSUE THREAD

**Issue by ahmedflix25** [Sascha-L/WPF-MediaKit#78]
* Does the problem emerge on different HW, OS versions? Describe your HW configuration.
yes
* Is the problem caused by the DirectShow codecs or the player itself?
player

1. the stop button on the test app work like the pause button it should return the playtime to 0 and preview image for the player

2. the player doesn't work on windows XP with microsoft visual c++, directx and lav filter installed also no mention in the wiki about the need for microsoft visual c++ 2015

3. the method to close the video doesn't dispose it from the player and it kept loaded without the ability to do anything to the file until i open another one

**Comment by xmedeko** [comment]
What renderer do you use? VMR9 should not need to install VS C++ redistributable. The EVR may need it, compile it with lower version by yourself if you need lower version of the redistributable.

About the Stop and Pause, you are right, they are same or similar. I do not know the details. Check DirectX `IMediaControl .Stop()` and `IMediaControl .Pause()`.

**Comment by ahmedflix25** [comment]
for xp i used the default settings only the test app atleat on my test machines needed the microsoft visual c++ 2015 or at least one dll file from it i can't recall it's name

the same settings on xp will get me an error when opening the app that some dll file from directx is missing and when i install it the app runs but it can't play anything and gives me an error for the player

**Comment by xmedeko** [comment]
Yes, this library works on most of machines, but sometimes one may found some problems. It's very hard to help you if you report "or at least one dll file from it i can't recall it's name". Also, this is a library, not player. You should have some C# programming knowledge to track down the problems.

Just try to switch to VMR9. Also check the error details in Debug.Trace output or configure [logging (see Wiki)](https://github.com/Sascha-L/WPF-MediaKit/wiki/Logging) if you cannot use Debug.Trace.

**Comment by skaterlui** [comment]
I think it's about the target framework version. The test app and the library targets .NET 4.5 
The last .NET framework version for xp was 4.0
https://docs.microsoft.com/en-gb/dotnet/framework/get-started/system-requirements

**Comment by xmedeko** [comment]
Well, if it's about .NET version I think the library may be compiled to .NET 4, but some minor changes will be necessary. Do you have some reason to use XP and not Windows 7?

**Comment by ahmedflix25** [comment]
nope, i rebuilt it targeting the dotnet 4.0 that why i could run the test app on XP but the player controller still give me an error when playing any video but the same dotnet 4.0 app runs ok on 7 8.1 and 10 with visual c++ 2015 installed without the need for the DirectX which was weird when the app itself ask for it on XP and wouldn't open
the player controller still give me an error unable to play anything after i installed the latest DirectX on xp

no, there isn't i was just testing the library and was wondering is it a bug with the library or someting i did?

**Comment by ahmedflix25** [comment]
https://imgur.com/a/HJerIjF

**Comment by xmedeko** [comment]
Well, `MF.dll` is a part of Media Foundation, I thnk it cannot be installed on WindowsXP. But better you check in by yourself. If not, then you have to use VMR9.

The error about the "Splitter graph" is caused by DirectX, do you have a [proper codecs installed](https://github.com/Sascha-L/WPF-MediaKit/wiki/Codecs)?   You must choose some lower version of K-Lite codecs which supports XP.

**Comment by ahmedflix25** [comment]
i will try again thanks

**Comment by ahmedflix25** [comment]
DirectX and Visual c++ is already installed + the latest LAV filter that supports XP

https://imgur.com/a/7bLe8FU

**Comment by xmedeko** [comment]
Yep, some VMs don't support DirectX, check dxdiag.exe -> Display -> Direct3D Acceleration.

**Comment by ahmedflix25** [comment]
yep, there is a problem with the VM i will try to test it on a real machine
