### ISSUE TITLE
MediaUriElement stops maintaining position and does not raise MediaEnded after restart

### ISSUE THREAD

**Issue by ecoChahn** [Sascha-L/WPF-MediaKit#8]
This is an open issue floating around the internet.  Does not look like the latest source addresses the issue.  

What I'm trying to do is manually loop the player at specific time-codes.  this works one time for me, and after that happens, checking position no longer is in-sync with actual playback.  I've also noticed that after I stop and start the player, it will not ever raise MediaEnded.

The solution seems to be in part adding a call to StartGraphPollTimer() inside MediaPlayerBase.Play().

**Comment by xmedeko** [comment]
+1. Yep, after the player reaches the end, the timer stops, so the `MediaPosition` is not maintained. I suggest to start the timer again in `Play()` method.

Workaround is to use `MediaUriElement Loop="True"` and then:
```` c#
video.MediaUriPlayer.MediaPositionChanged += MediaUriPlayer_MediaPositionChanged;
// ...
        private void MediaUriPlayer_MediaPositionChanged(object sender, System.EventArgs e)
        {
            if (video.MediaUriPlayer.MediaPosition >= video.MediaUriPlayer.Duration)
                this.Dispatcher.BeginInvoke(new Action(() => video.Stop()));
        }

**Comment by ecoChahn** [comment]
Thanks xmedeko.  Yeah, putting another call to StartGraphPollTimer() inside the Play() method of MediaPlayerBase does seem to get everything I need working.  I'm just not sure if that has other unintended effects.  I suppose just as long as I make sure it is always stopped at some point should be fine.
