### ISSUE TITLE
MediaUriElement play transparent movie with alpha channel?

### ISSUE THREAD

**Issue by Nic1628** [Sascha-L/WPF-MediaKit#87]
I am a beginner in vs. I read lots of articles, but It’s too difficult for me. 

Anybody have the full source code for playing transparent movie with alpha channel by using MediaUriElement?

Can it play in WPF VB project ?

Thanks very much !

**Comment by xmedeko** [comment]
It's not possible, there are some workarounds, see the whole discussion in #45:

- Do the color keying - choose one color and change it to transparent and use `MediaUriElement.Effect`. 
-  Try another filter (HAP, ffdshow - but it's quite obsolete, https://www.visioforge.com/fmpeg-source-filter.html, ...)
- Do the animated PNG.
- Try some FFmpeg or Vlc base player (e.g. see [Wiki Similar Projects](https://github.com/Sascha-L/WPF-MediaKit/wiki/Similar-Projects)).

**Comment by Nic1628** [comment]
Dear Sir/Madam,

I'm using WPFMediaKit - Videocaptureelement for my school project to capture video from HDMI USB Capture card. However there is no sound, it can display the screen only.

How to activate the sound/audio from the HDMI signal ?

On the other hand, Can I record selected portion of the screen with audio signal, 
and saved to wmv/mp4 file ?

Anybody can help me please ?


Thanks very much !
NIC

⁣

發送自 TypeApp

​

2018年9月10日 下午3:26, 下午3:26，在 Ondrej Medek <notifications@github.com> 已写:

**Comment by xmedeko** [comment]
@Nic1628 this issue is about image transparency, not sound. You have already asked at SO https://stackoverflow.com/questions/53748497 so wait for reply.
