### ISSUE TITLE
SpeedRatio is not working

### ISSUE THREAD

**Issue by miguelgomezmunoz** [Sascha-L/WPF-MediaKit#88]
First of all I am aware that there is a similar thread about this problem: https://github.com/Sascha-L/WPF-MediaKit/issues/34

I try to change the SpeedRatio after the mediaUriElement is loaded and open, I am using H.264 videos with K-Lite-Codec-Pack 995 and LAV, but the video goes always at the same speed (I have tried from 0.25 to 4).

Any solution?

**Comment by xmedeko** [comment]
@miguelgomezmunoz are you use LAV filter is used? `MediaUriPlayer` tries to open the video with LAV filters (`OpenSource()`) and if it fails it opens it with the default graph (`oldOpenSource()`).

**Comment by miguelgomezmunoz** [comment]
> @miguelgomezmunoz are you use LAV filter is used? MediaUriPlayer tries to open the video with LAV filters (OpenSource()) and if it fails it opens it with the default graph (oldOpenSource()).

I checked it again, it never uses the oldOpenSource() method and a new LAV filter icon appears in the taskbar for every video I open.

**Comment by xmedeko** [comment]
Can you test it with the Test Application frm this git repo and post your code changes or make a fork and then post a link to your fork and branch?

**Comment by xmedeko** [comment]
Yes, it would be some codec thing. Firts try to check the graph used, e.g. use `MediaUriElement.DumpGraphInfo()`. Then check the used filter, for which video file types it supports the speed ratio.
