### ISSUE TITLE
suggestion: not requiring any codecs

### ISSUE THREAD

**Issue by jtorjo** [Sascha-L/WPF-MediaKit#91]
Hi guys,

This was asked before - #43 . 
In my commercial project , I can't use Lavfilters (they're GPL), and I can't really tell the user to install K-lite codecs.

WPF MediaElement' works - but it's buggy as hell. So since I can open an .mp4 with the default MediaElement, I'm assuming everything is already installed. What am I missing?

**Comment by xmedeko** [comment]
WPF `MediaElement` is based on MediaFoundation. This project is based on DirectX DirectShow. They are different, incompatible technologies. If you are concerned about licence, try another [DirectShow codecs](https://github.com/Sascha-L/WPF-MediaKit/wiki/Codecs) or Google to find more. Or try other WPF player, see [Similar Projects](https://github.com/Sascha-L/WPF-MediaKit/wiki/Similar-Projects). Or you have to got with the WPF `MediaElement`.
