### ISSUE TITLE
Could not add SpliterSource to graph

### ISSUE THREAD

**Issue by lookitskris** [Sascha-L/WPF-MediaKit#92]
Hit this issue when trying to run the client app under 64bit.

Clone Repo
Run App
Load video -> Runs fine :D
Right click "Test Application", Properties, Build Tab, change "Platform Target" to x64 or AnyCPU
Run App
Load video -> exception "Could not add SpliterSource to graph" :(

This is the simplist repro I could manage as I ran into this error trying to use the library in a 64bit app.

Is there a fix? Something obvious i'm missing?

Kris

**Comment by xmedeko** [comment]
Check, you have proper codecs installed https://github.com/Sascha-L/WPF-MediaKit/wiki/Codecs

**Comment by lookitskris** [comment]
Thanks. is there a way to use just MF as a player, with no need for codecs out of the box? Or does this need additional work? asking before I jump in

**Comment by xmedeko** [comment]
Use the original WPF `MediaElement` unless you are really sure you need DirectX video. If so, you can distribute LAVFilters or other filters with your app and load them somehow (I do not experience with that, see `FilterFromFile`), but you must not break licence when distributing the filters.

**Comment by xmedeko** [comment]
Closing due to the inactivity.
