### ISSUE TITLE
Missing references in nuget

### ISSUE THREAD

**Issue by sekulicb** [Sascha-L/WPF-MediaKit#97]
When you add nuget package, and drop the VideoCaptureElement to XAML designer, Visual Studio complains that it cannot find the WPFMediaKit.dll. Right now it works if I add it manually as reference but it silly to add it as reference and pull it as nuget package. I see this is somewhat similar to #60 and still not resolved.

Thanks

**Comment by xmedeko** [comment]
Yes, it's duplicate to #60
